project:
  type: book
  output-dir: ../docs

# Oustanding problems: Footer, MVH's affiliation order;
# make it prettier

book:
  title: "Exemptions in Cook County's Property Tax System"
  subtitle: "Who Reaps the Benefits and Who Bears the Burdens"

  author:
  ## Alea info
  - name: Alea Wilbur-Mujtaba
    url: www.new-fancy-website.com
    email: awilbu2@uic.edu
    degrees:
      - MPA
    affiliations:
      - id: gfrc
        name: Governance Finance Research Center
        department: UIC College of Urban Planning and Public Affairs
        city: Chicago
        state: IL
        url: https://gfrc.uic.edu/
      - id: UIC
        name: University of Illinois Chicago
        city: Chicago
        state: IL
    attributes:
      corresponding: true ## Sorry--we can rearrange so the black helicopters get me first.
    #GET AN ORCID SO EZ
    orcid: ##########

#theoretically, shouldn't need to repeat the UIC info twice...but then it doesn't
#show up in the right order for me.

  ## MVH info
  - name: Michael P. Van Hulle
    url: www.new-fancy-website.com
    email: mvanhu2@uic.edu
    affiliations:
    - id: ngl
      name: Networks & Governance Lab
      department: Department of Public Policy, Management, and Analytics
      city: Chicago
      state: IL
      url: https://cuppa.uic.edu/net-gov-lab/
    - id: UIC
      name: University of Illinois Chicago
      city: Chicago
      state: IL
    degrees:
      - MA
      - JD
    orcid: 0009-0003-0301-9532

# I think we only want to manually update the date.

  date: "last updated March 7, 2024"

  #Index

  # Right now, the left ToC is "inter-page" while the left ToC is "intra-page."
  # Is that what we want?

  chapters:
    - index.qmd
    - GetData.qmd
    - breakeven-points.qmd
    - GHE_Scenarios.qmd
  #  - Exemption_Progressivity.qmd
    - milliondollarhomes.qmd
  #  - takeuprate.qmd

# MVH question: Why is the "left" section commented out? Still appears?
  navbar:
    right:
      - icon: github
        href: https://github.com/AleaWM/CookCounty-PropertyTaxes.git
  # left:
   #  - text: "About"
    #   file: index.qmd
     #- text: "Topics"

## MVH Note: I don't entirely know how the footer will appear.

format:
  html:
    theme: materia
    toc: true
    number-sections: false
    header-includes: |
      <link href='https://fonts.googleapis.com/css?family=Mukta' rel='stylesheet' type='text/css'>
    mainfont: Mukta

    #Code Options
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true

    #Figure and table options
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged

    #Footer options
    body-footer: |
      (c) 2024 Alea Wilbur-Mujtaba & Michael Van Hulle
      Work in progress for informational purposes only.
      Do not cite without permission.



#bibliography: references.bib
#reference-location: margin
#citation-location: margin



editor: visual

