project:
  type: book
  output-dir: ../docs

book:
  title: "Exemptions in Cook County's Property Tax System"
  subtitle: "Who Reaps the Benefits and Who Bears the Burdens"

  author:
  ## Alea info
  - name: Alea Wilbur-Mujtaba
  # url: www.new-fancy-website.com
    email: awilbu2@uic.edu
    degrees:
      - MPA
    affiliations:
    - id: gfrc
      name: Governance Finance Research Center
      city: Chicago
      state: IL
    - id: dppma
      name: Department of Public Policy, Management, and Analytics, University of Chicago Illinois
      city: Chicago
      state: IL
    attributes:
      corresponding: true ## Sorry--we can rearrange so the black helicopters get me first.
    #GET AN ORCID SO EZ
    orcid: ##########
  ## MVH info
  -name: Michael P. Van Hulle
  # url: www.new-fancy-website.com
    email: mvanhu2@uic.edu
    affiliations:
    - id: ngl
      name: Networks & Governance Lab
      city: Chicago
      state: IL
    - ref: dppma
    degrees:
      - MA
      - JD
    orcid: 0009-0003-0301-9532


  date: "last updated March 7, 2024" #I don't think we want the website to
  #self-identify as having updated unless we want it to?
  chapters:
    - index.qmd
    - GetData.qmd
    - breakeven-points.qmd
    - GHE_Scenarios.qmd
  #  - Exemption_Progressivity.qmd
    - milliondollarhomes.qmd
    - takeuprate.qmd

## MVH Note: I don't entirely know how these will appear, particularly the footer.

format:
  html:
    theme: darkly #I will fight you on this.
    toc: true
    #Code Options
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    #Figure and table options
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged
    #Footer options
    body-footer: |
      (c) 2024 Alea Wilbur-Mujtaba & Michael Van Hulle
      Work in progress for informational purposes only.
      Do not cite without permission.

  navbar:
    right:
  #we can do better!!!!!!
      - icon: github
       #icon: ^^^^^batman?
        href: https://github.com/AleaWM/CookCounty-PropertyTaxes.git
    left:
      - text: "About"
        file: index.qmd
      - text: "Topics"





#bibliography: references.bib
#reference-location: margin
#citation-location: margin



editor: visual

