project:
  type: book
  output-dir: ../docs

book:
  title: "Property Taxes in Cook County"
  subtitle: "Supplementary Data & Analysis"
  author: "Alea Wilbur-Mujtaba & Michael Van Hulle"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Exemption Whitepaper"
      chapters:
        - exemp_report_2021.qmd
        - exemp_report_2022.qmd
        - exemp_report_2023.qmd
    - part: "Exemption Addendum"
      chapters:
        - exemption_addendum_2021.qmd
        - exemption_addendum_2022.qmd
        - exemption_addendum_2023.qmd
        # - incentive_report_content.qmd
        # - incentive_report_2022.qmd
        # - incentive_report_2023.qmd
        
  #  - part: "Additional Analysis"
#      chapters:
       #   - takeup_rate?


  navbar: 
    right: 
      - icon: github
        href: https://github.com/AleaWM/CookCounty-PropertyTaxes.git


format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged
    number-sections: false


