project:
  type: book
  output-dir: ../docs

book:
  title: "Property Taxes in Cook County"
  subtitle: "Supplementary Data & Analysis"
  author: "Alea Wilbur-Mujtaba & Michael Van Hulle"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - exemption_report_content.qmd
        - exemption_report_2023update.qmd
        - exemption_addendum.qmd
        - incentive_report_content.qmd
  #  - part: "Additional Content"
  #    chapters:
       # - Exemption_Progressivity.qmd
      #  - breakeven-points.qmd


  navbar: 
    right: 
      - icon: github
        href: https://github.com/AleaWM/CookCounty-PropertyTaxes.git
    # left:
    #   - text: "About"
    #     file: index.qmd
    #   - text: "Topics"

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged
    execute:
      freeze: auto  # re-render only when source changes



