project:
  type: book
  output-dir: ../docs

book:
  title: "Property Taxes in Cook County"
  subtitle: "Supplementary Data & Analysis"
  author: "Alea Wilbur-Mujtaba & Michael Van Hulle"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - exemption_report_content.qmd
        - incentive_report_content.qmd
  #  - part: "Additional Content"
    #  chapters:
      #  - exemption_progressivity.qmd
     #   - breakeven-pints.qmd
   # - exemption_use.qmd
   # - exemption_tax_rates.qmd
   # - exemption_burden_shift.qmd
  #  - median_taxpayer.qmd
 #   - tax_code_intra_muni.qmd
   # - exemption_zero_dollar_paying.qmd
#   - Misc - covid & TIFs
#    - Methodology and stuff.


  navbar: 
    right: 
      - icon: github
        href: https://github.com/AleaWM/CookCounty-PropertyTaxes.git
    # left:
    #   - text: "About"
    #     file: index.qmd
    #   - text: "Topics"

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged



