project:
  type: book
  output-dir: ../docs

book:
  title: "Summary Statistics and Findings using CCAO's PTAXSIM package"
  subtitle: "Bonus research done by the GFRC RAs"
  author: "Alea Wilbur-Mujtaba & Michael Van Hulle"
  date: last-modified
  chapters:
    - index.qmd
    - GetData.qmd
    - breakeven-points.qmd
    - GHE_Scenarios.qmd
  #  - Exemption_Progressivity.qmd
    - milliondollarhomes.qmd
    - takeuprate.qmd


  navbar: 
    right: 
      - icon: github
        href: https://github.com/AleaWM/CookCounty-PropertyTaxes.git
    left:
      - text: "About"
        file: index.qmd
      - text: "Topics"

format:
  html:
    theme: darkly
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged

    

#bibliography: references.bib
#reference-location: margin
#citation-location: margin



editor: visual

